name: CI

on:
  pull_request:
  push:
    branches:
      - "master"
    tags:
      - "[0-9].[0-9].[0-9]"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.0
  tests:
    runs-on: ${{ matrix.machine }}
    strategy:
      matrix:
        include:
          - python-version: "3.6"
            machine: ubuntu-20.04
          - python-version: "3.7"
            machine: ubuntu-22.04
          - python-version: "3.8"
            machine: ubuntu-22.04
          - python-version: "3.9"
            machine: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install tox
        run: python -m pip install tox tox-gh-actions
      - name: Run tox
        run: python -m tox
      - name: Coveralls
        run: |
          python -m pip install codecov
          codecov
  deploy:
    runs-on: ubuntu-latest
    needs:
      - pre-commit
      - tests
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install pypa/build
        run: python -m pip install build
      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
